export const actionTypes = {
  FETCH_ALBUMS_AND_USERS_PENDING: "FETCH_ALBUMS_AND_USERS_PENDING",
  FETCH_ALBUMS_AND_USERS_SUCCESS: "FETCH_ALBUMS_AND_USERS_SUCCESS",
  FETCH_ALBUMS_AND_USERS_FAILED: "FETCH_ALBUMS_AND_USERS_FAILED",
};
